# Generated by Django 4.2.1 on 2023-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
